-- GitHub metadata/mapping foundation. Credentials are not stored in the database.
create type public.github_connection_status as enum ('NOT_CONNECTED','CONNECTED','ERROR');
create type public.github_sync_status as enum ('NOT_CONNECTED','CONNECTED','SYNCING','SYNCED','ERROR');
create table public.github_connections (id uuid primary key default gen_random_uuid(), connection_name text not null, github_owner text, installation_reference text, status public.github_connection_status not null default 'NOT_CONNECTED', last_checked_at timestamptz, last_error text, created_at timestamptz not null default timezone('utc',now()), updated_at timestamptz not null default timezone('utc',now()));
create table public.github_repositories (id uuid primary key default gen_random_uuid(), connection_id uuid not null references public.github_connections(id) on delete cascade, github_repository_id text not null, owner text not null, name text not null, private boolean not null default true, default_branch text not null default 'main', repository_url text, latest_commit text, latest_commit_message text, latest_commit_at timestamptz, created_at timestamptz not null default timezone('utc',now()), updated_at timestamptz not null default timezone('utc',now()), unique(connection_id,github_repository_id));
create table public.website_github_mappings (id uuid primary key default gen_random_uuid(), website_id uuid not null unique references public.websites(id) on delete cascade, tenant_id uuid not null references public.customer_accounts(id) on delete cascade, repository_id uuid not null unique references public.github_repositories(id) on delete restrict, source_path text not null default '/', sync_status public.github_sync_status not null default 'CONNECTED', last_synced_at timestamptz, last_error text, created_at timestamptz not null default timezone('utc',now()), updated_at timestamptz not null default timezone('utc',now()));
create table public.github_sync_logs (id uuid primary key default gen_random_uuid(), mapping_id uuid not null references public.website_github_mappings(id) on delete cascade, tenant_id uuid not null references public.customer_accounts(id) on delete cascade, status public.github_sync_status not null, commit_sha text, message text, created_at timestamptz not null default timezone('utc',now()));
create or replace function public.validate_website_github_mapping_scope() returns trigger language plpgsql set search_path='' as $$ declare website_tenant uuid; begin if auth.uid() is null or not public.is_master_admin() then raise exception 'Only Master Admin can manage GitHub mappings'; end if; select tenant_id into website_tenant from public.websites where id=new.website_id; if website_tenant is null then raise exception 'Website is not available'; end if; new.tenant_id:=website_tenant; return new; end; $$;
create trigger website_github_mappings_validate_scope before insert or update on public.website_github_mappings for each row execute function public.validate_website_github_mapping_scope();
create trigger github_connections_updated before update on public.github_connections for each row execute function public.set_updated_at(); create trigger github_repositories_updated before update on public.github_repositories for each row execute function public.set_updated_at(); create trigger website_github_mappings_updated before update on public.website_github_mappings for each row execute function public.set_updated_at();
alter table public.github_connections enable row level security; alter table public.github_repositories enable row level security; alter table public.website_github_mappings enable row level security; alter table public.github_sync_logs enable row level security;
create policy github_connections_master_manage on public.github_connections for all to authenticated using(public.is_master_admin()) with check(public.is_master_admin()); create policy github_repositories_master_manage on public.github_repositories for all to authenticated using(public.is_master_admin()) with check(public.is_master_admin()); create policy website_github_mappings_master_manage on public.website_github_mappings for all to authenticated using(public.is_master_admin()) with check(public.is_master_admin()); create policy website_github_mappings_customer_select on public.website_github_mappings for select to authenticated using(tenant_id=public.current_tenant_id()); create policy github_sync_logs_master_select on public.github_sync_logs for select to authenticated using(public.is_master_admin());
create or replace function public.audit_github_mapping_change() returns trigger language plpgsql security definer set search_path='' as $$ begin insert into public.audit_logs(actor_id,tenant_id,website_id,action,resource_type,resource_id,metadata) values(auth.uid(),coalesce(new.tenant_id,old.tenant_id),coalesce(new.website_id,old.website_id),case when tg_op='INSERT' then 'GITHUB_REPOSITORY_LINKED' else 'GITHUB_REPOSITORY_UNLINKED' end,'website_github_mapping',coalesce(new.id,old.id),'{}'::jsonb); return coalesce(new,old); end; $$;
create trigger website_github_mappings_audit after insert or delete on public.website_github_mappings for each row execute function public.audit_github_mapping_change();
revoke execute on function public.validate_website_github_mapping_scope() from public,authenticated; revoke execute on function public.audit_github_mapping_change() from public,authenticated;
