grant select on table public.customer_accounts to authenticated;
grant select, update on table public.profiles to authenticated;
grant select, insert, update, delete on table public.websites to authenticated;
grant select, insert, update, delete on table public.website_capabilities to authenticated;
grant select, insert, update, delete on table public.website_content to authenticated;
grant select, insert, update, delete on table public.media to authenticated;
grant select, insert, update, delete on table public.social_links to authenticated;
grant select, insert, update on table public.support_requests to authenticated;
grant select, insert on table public.support_messages to authenticated;
grant select on table public.support_access_grants to authenticated;
grant select on table public.audit_logs to authenticated;
grant select, insert, update, delete on table public.website_templates to authenticated;
grant select, insert, update, delete on table public.website_pages to authenticated;
grant select, insert, update, delete on table public.content_safety_reviews to authenticated;
grant select, insert, update, delete on table public.content_safety_findings to authenticated;
grant select, insert, update, delete on table public.commercial_agreements to authenticated;
grant select, insert, update, delete on table public.commercial_agreement_items to authenticated;
grant select, insert, update, delete on table public.commercial_agreement_documents to authenticated;
grant select on table public.commercial_agreement_history to authenticated;
grant select, insert, update, delete on table public.github_connections to authenticated;
grant select, insert, update, delete on table public.github_repositories to authenticated;
grant select, insert, update, delete on table public.website_github_mappings to authenticated;
grant select, insert, update, delete on table public.cloudflare_accounts to authenticated;
grant select, insert, update, delete on table public.cloudflare_zones to authenticated;
grant select, insert, update, delete on table public.cloudflare_deployments to authenticated;
grant select on table public.contact_enquiries to authenticated;
grant update on table public.contact_enquiries to authenticated;
grant select, insert, update, delete on table public.website_feature_inventory to authenticated;